services:
  todo-backend:
    build: .
    ports:
      - '${EXPOSED_PORT}:8080'
    volumes:
      - '.:/code'
    depends_on:
      - postgres
    env_file:
      - '.env'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 300M
        reservations:
          cpus: '1.50'
          memory: 100M
  postgres:
    env_file:
      - '.env'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
