spring:
  application:
    name: todoapp
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET:DASISTEINSEHRGUTESSECRETTEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSTTESTTEST}
logging:
  level:
    root: debug