spring:
  application:
    name: todoapp
jwt:
  secret: ${JWT_SECRET:DASISTEINSEHRGUTESSECRETTEkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkSTTESTTEST}
logging:
  level:
    root: debug